### PR TITLE
Store types in ir

### LINKED ISSUE #52: Store types in intermediate representation
[typeUsesOtherType](https://github.com/kornilova-l/scala-native-bindgen/blob/master/bindgen/Utils.h#L101) function checks if type is used in other type by simply comparing strings.  
This approach will fail on more complex types.

It would be better not to convert a type directly to string but to store it in intermediate representations.  
There will be a class `Type` that stores either string (for example `native.CInt`) or a pointer to other IR instance: `Struct`, `Union` or `Enum`.

Also there will be following subclasses of `Type`:
* `PointerType`
* `ArrayType`
* `FunctionPointerType`

All above classes will store pointer(s) to other types

### PR DESCRIPTION
**Pull request by kornilova-l**
Closes #52

Added multiple new classes in `ir/types` directory. I decided not to wrap `struct`/`union`/`enum` into a `Type` class instance but inherit the classes from `Type`.

One of changes:
Typedefs for `struct`/`union`/`enum` are generated right after a declaration was visited.
Example of such typedef:
```scala
type struct_point = native.CStruct2[native.CInt, native.CInt]
```
Created typedef points to `struct`/`union`/`enum` instance and it is added to translation map, so all other declarations that use type of this `struct`/`union`/`enum` will point to the created _typedef_.

I will carefully review the code later.

### CODE REVIEW

File: tests/samples/Struct.scala [hunk 1]
```diff
@@ -6,8 +6,8 @@ import scala.scalanative.native._
 @native.link("bindgentests")
 @native.extern
 object Struct {
-  type point_s = native.Ptr[struct_point]
   type struct_point = native.CStruct2[native.CInt, native.CInt]
+  type point_s = native.Ptr[struct_point]
```
Comment (jonas) [inline tests/samples/Struct.scala]: 👍

File: tests/samples/Typedef.scala [hunk 2]
```diff
@@ -6,12 +6,12 @@ import scala.scalanative.native._
...
 @native.extern
 object Typedef {
+  type enum_days = native.CUnsignedInt
+  type enum_toggle_e = native.CUnsignedInt
   type toggle_e = enum_toggle_e
   type int2int = native.CFunctionPtr1[native.CInt, native.CInt]
   type day2string = native.CFunctionPtr1[enum_days, native.CString]
   type toggle = native.CFunctionPtr1[toggle_e, Unit]
-  type enum_days = native.CUnsignedInt
-  type enum_toggle_e = native.CUnsignedInt
```
Comment (jonas) [inline tests/samples/Typedef.scala]: It looks like you are doing a lot of refactoring. Would you mind to split out things like reordering of the generated code to a separate PR?

File: bindgen/ir/types/SimpleType.h [hunk 3]
```diff
@@ -0,0 +1,24 @@
+#ifndef SCALA_NATIVE_BINDGEN_SIMPLETYPE_H
+#define SCALA_NATIVE_BINDGEN_SIMPLETYPE_H
+
+#include "Type.h"
+#include <string>
+
+/**
+ * For example native.CInt
+ */
+class SimpleType : public Type {
```
Comment (jonas) [inline bindgen/ir/types/SimpleType.h]: I suggest to name it `PrimitiveType`.

File: tests/samples/Typedef.scala (hunk 2 above)
Comment (kornilova-l) [reply tests/samples/Typedef.scala]: Generated code is reordered because typedefs are now generated earlier. Order of types happens to be more logical but it is not a separate refactoring

File: bindgen/ir/types/SimpleType.h (hunk 3 above)
Comment (kornilova-l) [reply bindgen/ir/types/SimpleType.h]: Name is good

**Comment by kornilova-l** [comment]
I tried to do memory management properly but got a problem:
Type instances are stored in other types and in such objects as `Field`. They can be deleted if they are not contained in IR (`struct`, `union`, `enum` or `typedef`). But the problem is that `vector<Field>` may copy-construct `Fields` and delete them that triggers destructor of `Type`.

It is not possible to use Type values instead of pointers because inheritance will not work properly. Using vectors of pointers for everything (so destructors are not called by `vector`) also does not seem to be a good idea.

I decided to not spend too much time on it and leave it as it is.

**Comment by jonas** [comment]
Okay, maybe we should create a ticket to investigate sometime in the future. I will take a second look when #62 has been merged and the conflict in this PR has been fixed.

File: bindgen/TypeTranslator.cpp [hunk 4]
```diff
@@ -68,111 +57,143 @@ TypeTranslator::TranslateFunctionPointer(const clang::QualType &qtpe,
...
     }
-    return name;
+    /* type has typedef alias */
+    return ir.getTypeDefWithName(name);
 }
 
-std::string
-TypeTranslator::TranslateConstantArray(const clang::ConstantArrayType *ar,
-                                       const std::string *avoid) {
+Type *TypeTranslator::translateEnum(const clang::QualType &qtpe) {
```
Comment (jonas) [inline bindgen/TypeTranslator.cpp]: It looks like this method is reused actually be used by `translateStruct` or even merged with it once the `union` specific `if` branch is removed.

File: bindgen/TypeTranslator.cpp [hunk 5]
```diff
@@ -68,111 +57,143 @@ TypeTranslator::TranslateFunctionPointer(const clang::QualType &qtpe,
...
     } else {
 
         auto found = typeMap.find(qtpe.getUnqualifiedType().getAsString());
         if (found != typeMap.end()) {
-            return handleReservedWords(found->second);
+            return new PrimitiveType(found->second);
         } else {
-            // TODO: Properly handle non-default types
-            return handleReservedWords(qtpe.getUnqualifiedType().getAsString());
+            return ir.getTypeDefWithName(
```
Comment (jonas) [inline bindgen/TypeTranslator.cpp]: I guess here we don't want to go through the alias map?

File: bindgen/TypeTranslator.h [hunk 6]
```diff
@@ -20,14 +14,38 @@ class TypeTranslator {
...
+
+    /**
+     * Primitive types
+     */
+    std::map<std::string, std::string> typeMap;
+
+    /**
+     * Maps C struct, union or enum name to Type alias
+     */
+    std::map<std::string, Type *> aliasesMap;
```
Comment (jonas) [inline bindgen/TypeTranslator.h]: I quite liked the unification in the original `typeMap`. Would it make sense to change it to be defined as:
```c++
std::map<std::string, Type *> typeMap
```
populated with
```c++
     typeMap["void"] = new PrimitiveType("Unit");
     typeMap["bool"] = new PrimitiveType("native.CBool");
     typeMap["_Bool"] = new PrimitiveType("native.CBool");
     // ...
```
I assume the problem is with the deallocation?

File: bindgen/defines/DefineFinder.cpp [hunk 7]
```diff
@@ -109,60 +111,63 @@ void DefineFinder::addNumericConstantDefine(const std::string &macroName,
                                             const clang::Token &token,
                                             bool positive) {
     clang::NumericLiteralParser parser(literal, token.getLocation(), pp);
-    std::string type;
+    Type *type = nullptr;
```
Comment (jonas) [inline bindgen/defines/DefineFinder.cpp]: This method could be simpler by using `std::string typeName` and still use `"native.CLongLong` etc. and do the `new PrimitiveType(typeName)` allocation at the end.

File: bindgen/ir/types/Type.cpp [hunk 8]
```diff
@@ -0,0 +1,8 @@
+#include "Type.h"
+#include "../../Utils.h"
+
+std::string Type::str() const { return handleReservedWords(_str()); }
```
Comment (jonas) [inline bindgen/ir/types/Type.cpp]: Won't this call `handleReservedWords()` on stuff like `native.CFunctionPtr[...]`? It seems that it over-do it. How hard would it be to selectively call it for any type that returns a simple `name` and then get rid of `_str()`?

File: bindgen/CycleDetection.h [hunk 9]
```diff
@@ -28,7 +28,12 @@ class CycleDetection {
             return;
         }
 
-        std::string qtpeString = tpeTransl.Translate(qtpe);
+        Type *type = tpeTransl.translate(qtpe);
+        if (type == nullptr) {
+            /* temp fix for function pointer */
```
[the remark this answers is not in the document]
Comment (kornilova-l) [reply bindgen/CycleDetection.h]: The function recursively extracts pointee type from pointer type to add a dependency.
So it extracts `FunctionType` from `FunctionPointerType` but `TypeTranslator` is unable to translate `FunctionType`
I'll make the comment more clear

File: bindgen/TypeTranslator.cpp [hunk 10]
```diff
@@ -68,111 +57,143 @@ TypeTranslator::TranslateFunctionPointer(const clang::QualType &qtpe,
...
         if (as->getKind() == clang::BuiltinType::Void) {
-            return "native.Ptr[Byte]";
+            return new PointerType(new PrimitiveType("Byte"));
         }
 
         // Take care of char*
         if (as->getKind() == clang::BuiltinType::Char_S ||
             as->getKind() == clang::BuiltinType::SChar) {
-            return "native.CString";
+            return new PrimitiveType("native.CString");
```
[the remark this answers is not in the document]
Comment (kornilova-l) [reply bindgen/TypeTranslator.cpp]: sure

File: bindgen/TypeTranslator.cpp [hunk 11]
```diff
@@ -68,111 +57,143 @@ TypeTranslator::TranslateFunctionPointer(const clang::QualType &qtpe,
...
     }
 
-    f = name.find(" ");
-    if (f != std::string::npos) {
-        return name.replace(f, std::string(" ").length(), "_");
+    auto it = aliasesMap.find(name);
+    if (it != aliasesMap.end()) {
+        /* name contains space: struct <name>.
+         * Use type alias instead struct type */
+        return (*it).second;
```
[the remark this answers is not in the document]
Comment (kornilova-l) [reply bindgen/TypeTranslator.cpp]: Consider following example:
```c
struct myStruct {
    int a;
};
```
Generated Scala code for the struct:
```Scala
type struct_myStruct = native.CStruct1[native.CInt]
```
Then we find the function that uses out struct:
```c
void myFunction(struct myStruct, s);
```
`TypeTranslator` would translate `struct myStruct` into `native.CStruct1[native.CInt]` but we want to use the alias `struct_myStruct`. We know that the alias already exists because struct was defined, so we find the alias in the map.

So we will reference a `TypeDef` instance generated for the struct

File: bindgen/TypeTranslator.cpp [hunk 12]
```diff
@@ -68,111 +57,143 @@ TypeTranslator::TranslateFunctionPointer(const clang::QualType &qtpe,
...
 }
 
-std::string
-TypeTranslator::TranslateStructOrUnion(const clang::QualType &qtpe) {
+Type *TypeTranslator::translateStruct(const clang::QualType &qtpe) {
     if (qtpe->hasUnnamedOrLocalType()) {
         // TODO: Verify that the local part is not a problem
         uint64_t size = ctx->getTypeSize(qtpe);
-        return "native.CArray[Byte, " + uint64ToScalaNat(size) + "]";
+        return new ArrayType(new PrimitiveType("Byte"), size);
```
[the remark this answers is not in the document]
Comment (kornilova-l) [reply bindgen/TypeTranslator.cpp]: Yes, I think so

File: bindgen/TypeTranslator.cpp (hunk 4 above)
Comment (kornilova-l) [reply bindgen/TypeTranslator.cpp]: :+1:

File: bindgen/TypeTranslator.cpp (hunk 5 above)
Comment (kornilova-l) [reply bindgen/TypeTranslator.cpp]: No, because `struct myStruct` will be translated above (the same for `enum` and `union`)

File: bindgen/TypeTranslator.h (hunk 6 above)
Comment (kornilova-l) [reply bindgen/TypeTranslator.h]: Yes, deallocation is the problem (well, these instances are not deallocated now, but changing type of the map will make fixing it harder)

Comment (kornilova-l) [reply bindgen/TypeTranslator.h]: I'll create an issue for deallocation

Comment (kornilova-l) [reply bindgen/TypeTranslator.h]: Or simply do it now, because I do not want the code that does not deallocate objects

File: bindgen/defines/DefineFinder.cpp (hunk 7 above)
Comment (kornilova-l) [reply bindgen/defines/DefineFinder.cpp]: :+1:

File: bindgen/ir/types/Type.cpp (hunk 8 above)
Comment (kornilova-l) [reply bindgen/ir/types/Type.cpp]: It shouldn't be a problem

File: bindgen/TypeTranslator.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (kornilova-l) [reply bindgen/TypeTranslator.cpp]: I found the case where it is used:
```c
struct myStruct {
    struct {
        int a;
    } innerStruct;
};
```
Currently this inner struct translates into array of bytes, but I suppose it will be better if we create a `type` for it. I'll create an issue for it

**Comment by kornilova-l** [comment]
But it is a bit ugly because some types are shared between objects (`Struct`, `Union`, `Enum` and `TypeDef`) and other `Type`s are stored in one object.
Now I think that it would be better not to inherit `Struct` (an other IR types) from `Type` but instead create wrappers of type `Type` so `Type` instances will not be created for each object and will not be shared

File: bindgen/TypeTranslator.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (jonas) [reply bindgen/TypeTranslator.cpp]: 👍
