### PR TITLE
Fix opaque types usages

### LINKED ISSUE #106: Replace unresolved opaque types with Byte if they are used only in pointers
Bindings for `uv.h` give following errors:
```
Error: type declaration for struct___fsid_t was not found.
Error: type declaration for struct___va_list_tag was not found.
Error: type declaration for struct__IO_FILE_plus was not found.
...
```
It happens when declaration of opaque type was not found.

Seems like it is not a problem but such cases should be handled carefully.

I checked couple of these types and they are used in one of following situations:
 * Only pointers to such type is used.
    In this case type may be replaced by `Byte`.
 * Type is used in a chain of unused typedefs.
    Whole chain may be removed in this case. Related to #13.
 * Extern variable of such type exist.
    In `uv.h` these variables are private, so they should be filtered.
    We do not know size of type so we cannot change type of extern to array of `Byte`
    I think, it is okay to always remove these extern variables.

### PR DESCRIPTION
**Pull request by kornilova-l**
Closes #106

Replaces pointers to opaque types with pointers to `Byte`
```c
struct undefinedStruct;
struct undefinedStruct *getUndefinedStruct();
```
```scala
def getUndefinedStruct(): native.Ptr[Byte] = native.extern
```
If there exists a declaration that uses an opaque type value then the declaration is skipped and error messages are printed:
```c
struct undefinedStruct;
extern struct undefinedStruct s;
```
```
Error: type definition for struct_undefinedStruct was not found.
Error: Variable s is skipped because it references an opaque type.
```

### CODE REVIEW

File: tests/samples/include/opaqueTypes.h [hunk 1]
```diff
@@ -0,0 +1,7 @@
+struct s;
```
Comment (jonas) [inline tests/samples/include/opaqueTypes.h]: Rename to start with upper case: `OpaqueTypes.h`

File: bindgen/ir/TypeDef.h [hunk 2]
```diff
@@ -23,6 +23,16 @@ class TypeDef : public TypeAndName, public Type {
...
 
+    /**
+     * @return true if typedef references opaque type directly or through a
+     * chain of typedefs.
+     */
+    bool referencesOpaqueType() const;
+
+    bool usesOpaqueType() const override;
+
+    using TypeAndName::replaceType;
```
Comment (jonas) [inline bindgen/ir/TypeDef.h]: Is this used?

File: tests/samples/OpaqueTypes.scala [hunk 3]
```diff
@@ -11,8 +11,16 @@ object OpaqueTypes {
   type struct_point = native.CStruct2[native.CInt, native.CInt]
   type union_u = native.CArray[Byte, native.Nat._4]
   type u = union_u
+  type struct_structWithPointerToUndefinedStruct = native.CStruct1[native.Ptr[Byte]]
+  type union_unionWithPointerToUndefinedStruct = native.CArray[Byte, native.Nat._8]
+  type aliasToPointerOfUndefinedUnion = native.Ptr[Byte]
+  type functionPointerWithPointerToOpaqueType = native.CFunctionPtr1[native.Ptr[native.Ptr[Byte]], native.Ptr[Byte]]
   def move(point: native.Ptr[struct_point], x: native.CInt, y: native.CInt): native.Ptr[struct_point] = native.extern
   def processPoints(p: native.Ptr[points]): native.Ptr[union_u] = native.extern
+  def usePointerToUndefinedStruct(anonymous0: native.Ptr[Byte]): Unit = native.extern
```
Comment (jonas) [inline tests/samples/OpaqueTypes.scala]: Looking at this I think it would be better to have

```scala

type struct_structWithPointerToUndefinedStruct = native.CStruct0
type union_unionWithPointerToUndefinedStruct = native.CArray[Byte, native.Nat._0] // not sure if 0 length is supported

def usePointerToUndefinedStruct(anonymous0: native.Ptr[struct_structWithPointerToUndefinedStruct]): Unit = native.extern
```

So `CStruct0` for opaque structs and then use the type alias in the pointers. With default opaque reprensentations  for structs and unions it should be possible to remove most use of replaceType except for updates to structs and unions.

File: bindgen/ir/types/PointerType.cpp [hunk 4]
```diff
@@ -23,3 +23,14 @@ bool PointerType::operator==(const Type &other) const {
     }
     return false;
 }
+
+bool PointerType::usesOpaqueType() const { return type->usesOpaqueType(); }
```
Comment (jonas) [inline bindgen/ir/types/PointerType.cpp]: A pointer to an opaque type is always sound, no?

File: tests/samples/OpaqueTypes.scala (hunk 3 above)
Comment (jonas) [reply tests/samples/OpaqueTypes.scala]: No helper class should be generated for such types.

File: tests/src/test/scala/org/scalanative/bindgen/BindgenSpec.scala [hunk 5]
```diff
@@ -38,10 +42,22 @@ class BindgenSpec extends FunSpec {
...
+          case "LiteralDefine.h" =>
+            assert(
+              errs == "Warning: integer value does not fit into 8 bytes: 18446744073709551615\n" +
+                "Warning: integer value does not fit into 8 bytes: 9223372036854775809")
+          case "OpaqueTypes.h" =>
+            assert(
+              errs == "Error: type definition for struct_undefinedStruct was not found.\n" +
+                "Error: Function useUndefinedStruct is skipped because it references an opaque type.")
+          case _ => assert(errs == "")
+        }
```
Comment (jonas) [inline tests/src/test/scala/org/scalanative/bindgen/BindgenSpec.scala]: To keep the tests clean, I would prefer to have checks for errors in a separate Spec.

File: bindgen/ir/TypeDef.h (hunk 2 above)
Comment (kornilova-l) [reply bindgen/ir/TypeDef.h]: `TypeDef` inherits from `Type` and `TypeAndName`, so we need to specify what version of `replaceType` should be used.
A typedef may contain pointer to opaque type that should be replaced with pointer to `Byte`:
```c
typedef struct s *s;
```
```scala
type s = native.Ptr[Byte]
```

File: tests/samples/OpaqueTypes.scala (hunk 3 above)
Comment (kornilova-l) [reply tests/samples/OpaqueTypes.scala]: Seems like a good solution.
Should we leave a comment beside `CStruct0` that it is an incomplete type or opaque type, so no one will think that it is indeed empty structure?

File: bindgen/ir/types/PointerType.cpp (hunk 4 above)
Comment (kornilova-l) [reply bindgen/ir/types/PointerType.cpp]: Yes, but by the time this method is called, all pointers to opaque type are replaced with pointers to `Byte`, so this method is used to finds illegal usages of opaque type

**Comment by kornilova-l** [comment]
Opaque types may be only `Struct` or `Union`, they are referenced only through corresponding pointers, so it is okay to replace `nullptr` in these `TypeDef`s with `CStruct0`.
But then we need to check if there are cases when the type is used as value. It may happen in these situations:
 * struct/union field of opaque type. This situation is illegal, Clang prints error `error: field has incomplete type` but it does not prevent construction of AST tree, so Scala Code is generated.
    I don't think that we should stop bindgen in this case because them problem may be related to inaccuracy in compilation database. It should be okay to remove such damaged structures and all code that uses them.
 * struct/union field of array type with elements of opaque type. The same situation as above.
 * function pointer type that uses value of opaque type.
    Clang does not print warning about it (why?), but I am not sure that generated code will be meaningful. In Scala Native such function pointers may exist but may they be executed?
 * function pointer type that uses array of opaque type. In this case Clang prints error (why?)
 * function uses value of opaque type. All functions that use values of structs or unions should be removed because it is not supported in Scala Native.
 * extern variable of opaque type. The variable and corresponding `VarDefines` may be safely removed.

**Comment by kornilova-l** [comment]
I decided not to remove structs with fields of opaque types because it is not normal situation, clangs prints error in this case.
Removing such structs and all declarations that use these structs will require relatively big amount of new code and it does not make a lot of sense because bindings cannot be correct if header files of compilation database is broken.

File: tests/src/test/scala/org/scalanative/bindgen/BindgenSpec.scala [hunk 6]
```diff
@@ -38,11 +48,35 @@ class BindgenSpec extends FunSpec {
...
+      it(s"should print correct warnings for ${input.getName}") {
+        val testName = input.getName.replace(".h", "")
+
+        val errs = bindgen(input, testName)
+
+        testName match {
+          case "LiteralDefine" =>
+            assert(
+              errs == "Warning: integer value does not fit into 8 bytes: 18446744073709551615\n" +
+                "Warning: integer value does not fit into 8 bytes: 9223372036854775809")
```
Comment (jonas) [inline tests/src/test/scala/org/scalanative/bindgen/BindgenSpec.scala]: Sorry for not being more clear, what I meant by _"have checks for errors in a separate Spec"_ was to do something like:

```scala
class BindgenReportingSpec extends FunSpec {
  it("Skip variable with opaque type") {
    val result = bindgen(
      input = "struct undefinedStruct;
              |extern struct undefinedStruct removedExtern;
              |#define removedExternAlias removedExtern
              |".stripMargin)
    assert(
      result.error == "Error: Variable alias removedExternAlias is skipped because it has incomplete type")
    )
  }
}
```
That is avoid mixing code with errors into the header files used by `BindgenSpec` and instead have focused tests.

I know it is a bit more work but I think the clarity it brings will pay off in the long run.

File: bindgen/ir/TypeDef.cpp [hunk 7]
```diff
@@ -9,14 +9,13 @@ TypeDef::TypeDef(std::string name, std::shared_ptr<Type> type,
...
-    if (!typeDef.getType()) {
-        llvm::errs() << "Error: type definition for " << typeDef.getName()
-                     << " was not found.\n";
-        llvm::errs().flush();
-        return s;
+    s << "  type " << handleReservedWords(typeDef.name) << " = ";
+    if (typeDef.type) {
+        s << typeDef.getType()->str();
+    } else {
+        s << "native.CStruct0 // incomplete type";
```
[the remark this answers is not in the document]
Comment (kornilova-l) [reply bindgen/ir/TypeDef.cpp]: I used _incomplete_ because it is the term that clang uses in error messages.

[the remark this answers is not in the document]
Comment (jonas) [reply bindgen/ir/TypeDef.cpp]: Okay makes sense then.
